package reposcaffold

import (
	"testing"

	"github.com/Azure/taugrid/cli/internal/workspaceconnection"
)

// TestMinTauVersionIsSatisfiedByTheGeneratingBinary is the guard against a
// scaffold that generates a repository its own generator cannot run.
//
// The descriptor's requirements.minTauVersion gates `tau run TARGET`. When it
// is pinned ahead of the shipped version, every generated repo fails with
// "install Tau X or newer" naming a version that does not exist — and the error
// blames the researcher, who cannot act on it.
//
// The cases are release-shaped on purpose. Feeding in the live version.Version
// would look like the strongest case and assert nothing: a test binary reports
// "dev", and CheckTauVersion returns nil for "dev" before comparing anything,
// so that case passes even for a floor of 99.0.0.
func TestMinTauVersionIsSatisfiedByTheGeneratingBinary(t *testing.T) {
	for _, current := range []string{"v0.1.3", "v1.0.0"} {
		if err := workspaceconnection.CheckTauVersion(current, minTauVersion(current)); err != nil {
			t.Fatalf("scaffold generated by Tau %s produced a repo it cannot run: %v", current, err)
		}
	}
}

// TestMinTauVersionIsValidDescriptorInput guards the other side: the value must
// still parse as a three-part version, including for unstamped `go build`
// binaries where version.Version is the literal "dev".
func TestMinTauVersionIsValidDescriptorInput(t *testing.T) {
	for _, current := range []string{"dev", "", "v0.1.3", "0.2.0-rc1"} {
		got := minTauVersion(current)
		if err := workspaceconnection.CheckTauVersion("v99.0.0", got); err != nil {
			t.Fatalf("minTauVersion(%q) = %q is not a parseable version: %v", current, got, err)
		}
	}
}

// TestMinTauVersionDerivesTheFloorFromTheBinary pins the derived values, not
// just that they parse. The tests above assert relations ("satisfies", "is
// parseable") that a constant 0.0.0 meets for free, so neither would notice the
// floor collapsing to 0.0.0 for every build — which disarms the gate outright.
//
// That matters because tau/workspace.connection.yaml is committed into the
// generated repo: a floor written once is what every later clone enforces.
//
// The "dev" row records a deliberate concession rather than an accident. An
// unstamped binary has no version to derive from, and 0.0.0 accepts any Tau. It
// is the right call for local `go build` use, and it is pinned here so that
// widening it to released binaries has to be a visible edit.
func TestMinTauVersionDerivesTheFloorFromTheBinary(t *testing.T) {
	for _, tc := range []struct{ current, want string }{
		{"v0.1.3", "0.1.0"},
		{"0.1.3", "0.1.0"},
		{"v1.2.9", "1.2.0"},
		{"v10.20.30", "10.20.0"},
		{"0.2.0-rc1", "0.2.0"},
		{"dev", "0.0.0"},
		{"", "0.0.0"},
	} {
		if got := minTauVersion(tc.current); got != tc.want {
			t.Errorf("minTauVersion(%q) = %q, want %q", tc.current, got, tc.want)
		}
	}
}
