# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: taugrid-local-preview
build:
  tagPolicy:
    inputDigest: {}
  platforms:
    - linux/amd64
  local:
    push: true
  artifacts:
    - image: tau
      context: .
      custom:
        buildCommand: ./scripts/skaffold-acr-build.sh tau
        dependencies:
          paths:
            - images/tau/Dockerfile
            - scripts/skaffold-acr-build.sh
            - cli/**
            - core/**
    - image: taugrid-portal
      context: .
      custom:
        buildCommand: ./scripts/skaffold-acr-build.sh taugrid-portal
        dependencies:
          paths:
            - images/taugrid-portal/Dockerfile
            - scripts/skaffold-acr-build.sh
            - portal/**
            - core/**
          ignore:
            - portal/frontend/node_modules/**
            - portal/frontend/*.tsbuildinfo
    - image: tau-core-controller
      context: .
      custom:
        buildCommand: ./scripts/skaffold-acr-build.sh tau-core-controller
        dependencies:
          paths:
            - images/tau-core-controller/Dockerfile
            - scripts/skaffold-acr-build.sh
            - controllers/tau-core/**
            - core/**
