//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesSubject) DeepCopyInto(out *KubernetesSubject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesSubject.
func (in *KubernetesSubject) DeepCopy() *KubernetesSubject {
	if in == nil {
		return nil
	}
	out := new(KubernetesSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrincipalRef) DeepCopyInto(out *PrincipalRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrincipalRef.
func (in *PrincipalRef) DeepCopy() *PrincipalRef {
	if in == nil {
		return nil
	}
	out := new(PrincipalRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauCluster) DeepCopyInto(out *TauCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauCluster.
func (in *TauCluster) DeepCopy() *TauCluster {
	if in == nil {
		return nil
	}
	out := new(TauCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TauCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauClusterList) DeepCopyInto(out *TauClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TauCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauClusterList.
func (in *TauClusterList) DeepCopy() *TauClusterList {
	if in == nil {
		return nil
	}
	out := new(TauClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TauClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauClusterNodesSpec) DeepCopyInto(out *TauClusterNodesSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LabelRules != nil {
		in, out := &in.LabelRules, &out.LabelRules
		*out = make([]TauNodeLabelRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauClusterNodesSpec.
func (in *TauClusterNodesSpec) DeepCopy() *TauClusterNodesSpec {
	if in == nil {
		return nil
	}
	out := new(TauClusterNodesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauClusterObjectReference) DeepCopyInto(out *TauClusterObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauClusterObjectReference.
func (in *TauClusterObjectReference) DeepCopy() *TauClusterObjectReference {
	if in == nil {
		return nil
	}
	out := new(TauClusterObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauClusterQueuesSpec) DeepCopyInto(out *TauClusterQueuesSpec) {
	*out = *in
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(TauClusterObjectReference)
		**out = **in
	}
	if in.ResourceFlavors != nil {
		in, out := &in.ResourceFlavors, &out.ResourceFlavors
		*out = make([]TauClusterObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.ClusterQueues != nil {
		in, out := &in.ClusterQueues, &out.ClusterQueues
		*out = make([]TauClusterObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.SharedLocalQueues != nil {
		in, out := &in.SharedLocalQueues, &out.SharedLocalQueues
		*out = make([]TauNamespacedObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauClusterQueuesSpec.
func (in *TauClusterQueuesSpec) DeepCopy() *TauClusterQueuesSpec {
	if in == nil {
		return nil
	}
	out := new(TauClusterQueuesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauClusterSectionStatus) DeepCopyInto(out *TauClusterSectionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauClusterSectionStatus.
func (in *TauClusterSectionStatus) DeepCopy() *TauClusterSectionStatus {
	if in == nil {
		return nil
	}
	out := new(TauClusterSectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauClusterSpec) DeepCopyInto(out *TauClusterSpec) {
	*out = *in
	in.Nodes.DeepCopyInto(&out.Nodes)
	in.Queues.DeepCopyInto(&out.Queues)
	out.WorkspaceDefaults = in.WorkspaceDefaults
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauClusterSpec.
func (in *TauClusterSpec) DeepCopy() *TauClusterSpec {
	if in == nil {
		return nil
	}
	out := new(TauClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauClusterStatus) DeepCopyInto(out *TauClusterStatus) {
	*out = *in
	out.Nodes = in.Nodes
	out.Queues = in.Queues
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make([]TauManagedResourceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauClusterStatus.
func (in *TauClusterStatus) DeepCopy() *TauClusterStatus {
	if in == nil {
		return nil
	}
	out := new(TauClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauClusterWorkspaceDefaults) DeepCopyInto(out *TauClusterWorkspaceDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauClusterWorkspaceDefaults.
func (in *TauClusterWorkspaceDefaults) DeepCopy() *TauClusterWorkspaceDefaults {
	if in == nil {
		return nil
	}
	out := new(TauClusterWorkspaceDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauManagedResourceStatus) DeepCopyInto(out *TauManagedResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauManagedResourceStatus.
func (in *TauManagedResourceStatus) DeepCopy() *TauManagedResourceStatus {
	if in == nil {
		return nil
	}
	out := new(TauManagedResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauNamespacedObjectReference) DeepCopyInto(out *TauNamespacedObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauNamespacedObjectReference.
func (in *TauNamespacedObjectReference) DeepCopy() *TauNamespacedObjectReference {
	if in == nil {
		return nil
	}
	out := new(TauNamespacedObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauNodeLabelRule) DeepCopyInto(out *TauNodeLabelRule) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauNodeLabelRule.
func (in *TauNodeLabelRule) DeepCopy() *TauNodeLabelRule {
	if in == nil {
		return nil
	}
	out := new(TauNodeLabelRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauNodeMatch) DeepCopyInto(out *TauNodeMatch) {
	*out = *in
	if in.VMSizes != nil {
		in, out := &in.VMSizes, &out.VMSizes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauNodeMatch.
func (in *TauNodeMatch) DeepCopy() *TauNodeMatch {
	if in == nil {
		return nil
	}
	out := new(TauNodeMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauQuotaRequest) DeepCopyInto(out *TauQuotaRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauQuotaRequest.
func (in *TauQuotaRequest) DeepCopy() *TauQuotaRequest {
	if in == nil {
		return nil
	}
	out := new(TauQuotaRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TauQuotaRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauQuotaRequestList) DeepCopyInto(out *TauQuotaRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TauQuotaRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauQuotaRequestList.
func (in *TauQuotaRequestList) DeepCopy() *TauQuotaRequestList {
	if in == nil {
		return nil
	}
	out := new(TauQuotaRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TauQuotaRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauQuotaRequestSpec) DeepCopyInto(out *TauQuotaRequestSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauQuotaRequestSpec.
func (in *TauQuotaRequestSpec) DeepCopy() *TauQuotaRequestSpec {
	if in == nil {
		return nil
	}
	out := new(TauQuotaRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauQuotaRequestStatus) DeepCopyInto(out *TauQuotaRequestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauQuotaRequestStatus.
func (in *TauQuotaRequestStatus) DeepCopy() *TauQuotaRequestStatus {
	if in == nil {
		return nil
	}
	out := new(TauQuotaRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauWorkspace) DeepCopyInto(out *TauWorkspace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauWorkspace.
func (in *TauWorkspace) DeepCopy() *TauWorkspace {
	if in == nil {
		return nil
	}
	out := new(TauWorkspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TauWorkspace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauWorkspaceList) DeepCopyInto(out *TauWorkspaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TauWorkspace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauWorkspaceList.
func (in *TauWorkspaceList) DeepCopy() *TauWorkspaceList {
	if in == nil {
		return nil
	}
	out := new(TauWorkspaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TauWorkspaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauWorkspaceSpec) DeepCopyInto(out *TauWorkspaceSpec) {
	*out = *in
	if in.Authorization != nil {
		in, out := &in.Authorization, &out.Authorization
		*out = new(WorkspaceAuthorization)
		**out = **in
	}
	if in.PrincipalRef != nil {
		in, out := &in.PrincipalRef, &out.PrincipalRef
		*out = new(PrincipalRef)
		**out = **in
	}
	if in.KubernetesSubject != nil {
		in, out := &in.KubernetesSubject, &out.KubernetesSubject
		*out = new(KubernetesSubject)
		**out = **in
	}
	out.Target = in.Target
	out.Defaults = in.Defaults
	if in.WorkloadIdentity != nil {
		in, out := &in.WorkloadIdentity, &out.WorkloadIdentity
		*out = new(WorkspaceWorkloadIdentity)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauWorkspaceSpec.
func (in *TauWorkspaceSpec) DeepCopy() *TauWorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(TauWorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TauWorkspaceStatus) DeepCopyInto(out *TauWorkspaceStatus) {
	*out = *in
	out.Target = in.Target
	out.Queue = in.Queue
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TauWorkspaceStatus.
func (in *TauWorkspaceStatus) DeepCopy() *TauWorkspaceStatus {
	if in == nil {
		return nil
	}
	out := new(TauWorkspaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceAuthorization) DeepCopyInto(out *WorkspaceAuthorization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceAuthorization.
func (in *WorkspaceAuthorization) DeepCopy() *WorkspaceAuthorization {
	if in == nil {
		return nil
	}
	out := new(WorkspaceAuthorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceDefaults) DeepCopyInto(out *WorkspaceDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceDefaults.
func (in *WorkspaceDefaults) DeepCopy() *WorkspaceDefaults {
	if in == nil {
		return nil
	}
	out := new(WorkspaceDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceQueueStatus) DeepCopyInto(out *WorkspaceQueueStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceQueueStatus.
func (in *WorkspaceQueueStatus) DeepCopy() *WorkspaceQueueStatus {
	if in == nil {
		return nil
	}
	out := new(WorkspaceQueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceTarget) DeepCopyInto(out *WorkspaceTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceTarget.
func (in *WorkspaceTarget) DeepCopy() *WorkspaceTarget {
	if in == nil {
		return nil
	}
	out := new(WorkspaceTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceTargetStatus) DeepCopyInto(out *WorkspaceTargetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceTargetStatus.
func (in *WorkspaceTargetStatus) DeepCopy() *WorkspaceTargetStatus {
	if in == nil {
		return nil
	}
	out := new(WorkspaceTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceWorkloadIdentity) DeepCopyInto(out *WorkspaceWorkloadIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceWorkloadIdentity.
func (in *WorkspaceWorkloadIdentity) DeepCopy() *WorkspaceWorkloadIdentity {
	if in == nil {
		return nil
	}
	out := new(WorkspaceWorkloadIdentity)
	in.DeepCopyInto(out)
	return out
}
