apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "tau-core-controller.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    helm.sh/resource-policy: keep
  labels:
    {{- include "tau-core-controller.labels" . | nindent 4 }}
    tau.azure.com/managed-by: gitops
