apiVersion: v1
kind: ServiceAccount
metadata:
  name: tau-core-controller
  namespace: {{ include "tau-core-controller.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    {{- include "tau-core-controller.labels" . | nindent 4 }}
