apiVersion: v1
kind: ServiceAccount
metadata:
  name: tau-core-controller
  namespace: tau-platform
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: tau-core-controller
    app.kubernetes.io/part-of: taugrid
