{{- if .Values.ingestor.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "adx-mon.fullname" . }}-ingestor
  labels:
    {{- include "adx-mon.componentLabels" (dict "root" . "component" "ingestor") | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [namespaces, pods]
    verbs: [get, list, watch]
  - apiGroups: [adx-mon.azure.com]
    resources: [functions, managementcommands, summaryrules]
    verbs: [get, list, update, patch]
  - apiGroups: [adx-mon.azure.com]
    resources: [functions/status, managementcommands/status, summaryrules/status]
    verbs: [update, patch]
  - apiGroups: [adx-mon.azure.com]
    resources: [functions/finalizers, managementcommands/finalizers, summaryrules/finalizers]
    verbs: [get, update, delete]
{{- end }}
