// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package cli

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// exampleRowGenerator imports the portal-ray-stellar example's metrics_row()
// and prints one real row. The example imports ray at module scope, which is
// not installed in CI, so stub the three ray modules it touches before import.
const exampleRowGenerator = `
import json, sys, types, importlib.util

for name in (
    "ray",
    "ray.train",
    "ray.train.torch",
    "ray.util",
    "ray.util.placement_group",
    "ray.util.scheduling_strategies",
):
    module = types.ModuleType(name)
    module.__getattr__ = lambda _attr: None
    sys.modules[name] = module
sys.modules["ray"].train = sys.modules["ray.train"]
sys.modules["ray"].util = sys.modules["ray.util"]
sys.modules["ray"].remote = lambda *_args, **_kwargs: lambda fn: fn
sys.modules["ray.train"].torch = sys.modules["ray.train.torch"]
sys.modules["ray.train"].ScalingConfig = object
sys.modules["ray.train.torch"].TorchTrainer = object
sys.modules["ray.util.placement_group"].placement_group = object
sys.modules["ray.util.placement_group"].remove_placement_group = object
sys.modules["ray.util.scheduling_strategies"].PlacementGroupSchedulingStrategy = object

spec = importlib.util.spec_from_file_location("portal_ray_stellar_train", sys.argv[1])
train = importlib.util.module_from_spec(spec)
spec.loader.exec_module(train)
print(json.dumps(train.metrics_row(7, 1.25, 0.75)))
`

// TestMetricsOffloadOnlineAcceptsPortalRayStellarExampleRow feeds a row
// generated by the example's own metrics_row() through the online offload
// validation and import path. It fails if the example ever regresses to an
// RFC3339 string _timestamp, which the offloader rejects with
// "_timestamp must be numeric" — leaving the demo's Stellar link dark.
func TestMetricsOffloadOnlineAcceptsPortalRayStellarExampleRow(t *testing.T) {
	python, err := exec.LookPath("python3")
	if err != nil {
		t.Skip("python3 not available")
	}
	script := filepath.Join("..", "..", "..", "examples", "portal-ray-stellar", "train.py")
	if _, err := os.Stat(script); err != nil {
		t.Fatalf("example script: %v", err)
	}

	cmd := exec.Command(python, "-c", exampleRowGenerator, script)
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("generate example row: %v", err)
	}
	row := strings.TrimSpace(string(out))

	history := filepath.Join(t.TempDir(), "chunk-000001.jsonl")
	if err := os.WriteFile(history, []byte(row+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	result, err := runMetricsOffloadOnce(context.Background(), newTestMetricsOffloadStore(t, "example-row"), metricsOffloadOptions{
		History:      []string{history},
		RunID:        "portal-ray-stellar",
		Project:      "portal-demo",
		ExperimentID: "ray-plus-stellar",
		RunGroupID:   "bounded",
		Source:       "stellar-online",
		Out:          filepath.Join(t.TempDir(), "out"),
	})
	if err != nil {
		t.Fatalf("example row rejected by online offloader: %v (row=%s)", err, row)
	}
	// The example row carries two scalar metrics (loss, accuracy), and the
	// offloader counts one import row per scalar.
	if result.ImportRows != 2 {
		t.Fatalf("import rows = %d, want 2 (row=%s)", result.ImportRows, row)
	}
	exported, err := os.ReadFile(result.MetricsFile)
	if err != nil {
		t.Fatalf("read exported metric rows: %v", err)
	}
	if !strings.Contains(string(exported), `"experiment_id":"ray-plus-stellar"`) {
		t.Fatalf("exported rows lost experiment identity:\n%s", exported)
	}
}
