{{- if .Values.operator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "adx-mon.fullname" . }}-operator
  labels:
    {{- include "adx-mon.componentLabels" (dict "root" . "component" "operator") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "adx-mon.fullname" . }}-operator
subjects:
  - kind: ServiceAccount
    name: {{ include "adx-mon.serviceAccountName" (dict "root" . "component" "operator") }}
    namespace: {{ include "adx-mon.namespace" . }}
{{- end }}
