"""Cluster-side runtime: the wrapper that runs on the Ray head pod.

This module is read as a string (`CLUSTER_WRAPPER_TEMPLATE`) by `tau.workloads`
and shipped to the cluster as `train.py` via `tau run --config`. It must be self-contained — the cluster image only
guarantees Python 3.10 + torch + the deps the entrypoint pip-installs. There
is **no** tau-py install on the cluster.

To make `import tau` work in the researcher's module on the cluster (since
tau-py isn't installed there), the wrapper installs a minimal in-memory
shim into `sys.modules["tau"]` *before* importlib loads the user module.
For eval Ray workers, it also writes the same shim as an importable package
inside the Ray runtime_env working_dir because sys.modules is process-local.
The shim's `train()` decorator returns the same `_TrainHandle`-shaped
object the local SDK does — but on the cluster its `.submit()` raises
(you can't submit from inside a job; you'd recurse).
"""

from importlib import resources


# The wrapper is a literal string so `tau.workloads` can ship it verbatim
# without needing to find this file at SDK runtime (matters for `pip
# install` from a wheel where __file__ paths get weird).
CLUSTER_WRAPPER_TEMPLATE = r'''#!/usr/bin/env python3
# Auto-generated by tau-py. Do not edit on the cluster.
# Source: sdk/python/tau/_cluster.py
"""Loads the researcher's module and invokes the @tau.train fn.

Runs as the bash entrypoint's `python3 /script/train.py` on the Ray head pod.
"""
import argparse
import datetime
import importlib.util
import inspect
import json
import os
import pathlib
import shutil
import subprocess
import sys
import threading
import time
import types

USER_MODULE_FILENAME = __USER_MODULE_FILENAME__
USER_MODULE_PATH = "/script/" + USER_MODULE_FILENAME


def _env_int(key, default):
    raw = os.environ.get(key, "")
    try:
        return int(raw) if raw else default
    except ValueError:
        return default


def _env_float(key, default):
    raw = os.environ.get(key, "")
    try:
        return float(raw) if raw else default
    except ValueError:
        return default


_COPY_PROGRESS_MIN_BYTES = max(0, _env_int("TAU_ARTIFACT_COPY_PROGRESS_MIN_BYTES", 256 * 1024 * 1024))
_COPY_PROGRESS_STEP_BYTES = max(1, _env_int("TAU_ARTIFACT_COPY_PROGRESS_STEP_BYTES", 1024 * 1024 * 1024))
_COPY_PROGRESS_INTERVAL_SECONDS = max(0.0, _env_float("TAU_ARTIFACT_COPY_PROGRESS_INTERVAL_SECONDS", 30.0))
_COPY_BUFFER_BYTES = 8 * 1024 * 1024


_TAU_SHIM_INIT = """from . import datasets as datasets
from . import entrypoints as entrypoints
from . import workloads as workloads
from . import jsonl as jsonl
from .config import SecretRef, config, load_config, pvc_mount, secret, secret_ref
from .datasets import dataset_file_reference
from .entrypoints import call_staged_function, load_staged_function, load_staged_module
from .workloads import Ctx, eval, train
from .jsonl import read_jsonl_objects

__all__ = [
    "Ctx",
    "SecretRef",
    "call_staged_function",
    "config",
    "dataset_file_reference",
    "datasets",
    "entrypoints",
    "eval",
    "jsonl",
    "load_config",
    "load_staged_function",
    "load_staged_module",
    "pvc_mount",
    "read_jsonl_objects",
    "secret",
    "secret_ref",
    "train",
    "workloads",
]
"""


_TAU_SHIM_CONFIG = """import copy
import json

_CLUSTER_MANIFEST = json.loads(__TAU_CLUSTER_MANIFEST_JSON__)


class SecretRef:
    def __init__(self, name, key):
        if not name or not key:
            raise ValueError("tau.secret_ref requires non-empty secret name and key")
        self.name = str(name)
        self.key = str(key)


def _manifest_copy():
    # The submitted manifest is the already-composed project config. On
    # cluster, do not reread project-owned YAML/TOML files that may not have
    # been staged; return the manifest snapshot instead.
    return copy.deepcopy(_CLUSTER_MANIFEST)


def load_config(source=None):
    return _manifest_copy()


def config(*sources, overrides=None, env=None):
    return _manifest_copy()


def secret_ref(name, key):
    return SecretRef(name, key)


def secret(name, key):
    return secret_ref(name, key)


def pvc_mount(name, *, pvc, mount_path, read_only=False):
    if not name or not pvc or not str(mount_path).startswith("/"):
        raise ValueError("tau.pvc_mount requires name, pvc, and an absolute mount_path")
    return {
        "name": str(name),
        "pvc": str(pvc),
        "mountPath": str(mount_path),
        "readOnly": bool(read_only),
    }


__all__ = ["SecretRef", "config", "load_config", "pvc_mount", "secret", "secret_ref"]
"""


_TAU_SHIM_DATASETS = __TAU_SHIM_DATASETS_SOURCE__
_TAU_SHIM_JSONL = __TAU_SHIM_JSONL_SOURCE__
_TAU_SHIM_ENTRYPOINTS = __TAU_SHIM_ENTRYPOINTS_SOURCE__


_TAU_SHIM_WORKLOADS = """class Ctx:
    pass


class _ClusterHandle:
    def __init__(self, fn, kwargs, kind):
        self._fn = fn
        self._kwargs = kwargs
        self.__name__ = getattr(fn, "__name__", kind)
        setattr(self, "_tau_" + kind + "_handle", True)

    def __call__(self, *a, **kw):
        raise RuntimeError(
            "tau-py: refusing to call the " + self.__name__ +
            " function directly inside a cluster-submitted job."
        )

    def submit(self, *a, **kw):
        raise RuntimeError(
            "tau-py: refusing to .submit() from inside a cluster-submitted job."
        )


def _decorator(kind):
    def _make(*args, **kwargs):
        if args:
            raise TypeError("tau." + kind + ": pass parameters as keyword arguments")

        def _wrap(fn):
            return _ClusterHandle(fn, dict(kwargs), kind)

        return _wrap

    return _make


train = _decorator("train")
eval = _decorator("eval")
"""


def _render_config_shim(manifest):
    manifest_json = json.dumps(manifest or {}, sort_keys=True)
    return _TAU_SHIM_CONFIG.replace("__TAU_CLUSTER_MANIFEST_JSON__", repr(manifest_json))


def _build_cluster_ctx(manifest_path, smoke_pairs):
    """Build a Ctx mirroring what the embedded Sample trainer would see."""
    import yaml  # part of the entrypoint pip install
    with open(manifest_path) as f:
        manifest = yaml.safe_load(f) or {}

    def _envp(key, default=""):
        v = os.environ.get(key, default)
        return pathlib.Path(v) if v else None

    class Ctx:
        pass

    ctx = Ctx()
    ctx.name = manifest.get("name", "")
    compute = manifest.get("compute") or {}
    ctx.gpus = int(compute.get("gpus", 0))
    # Default workers to 1 so an older manifest (no compute.workers)
    # behaves byte-identically to the v1.0 single-node path.
    ctx.workers = int(compute.get("workers", 1) or 1)
    ctx.smoke_pairs = int(smoke_pairs)
    ctx.manifest = manifest
    ctx.manifest_path = pathlib.Path(manifest_path)
    ctx.data_dir = _envp("TAU_DATA_DIR", "/data")
    ctx.hot_dir = _envp("TAU_HOT_DIR", "/mnt")
    ctx.datasets_dir = _envp("TAU_DATASETS_DIR", "/mnt/datasets")
    ctx.checkpoints_dir = _envp("TAU_CHECKPOINTS_DIR", "/mnt/checkpoints")
    ctx.durable_datasets_dir = _envp("TAU_DURABLE_DATASETS_DIR", "/data/datasets")
    ctx.durable_checkpoints_dir = _envp("TAU_DURABLE_CHECKPOINTS_DIR", "/data/checkpoints")
    ctx.storage_hot_status = os.environ.get("TAU_STORAGE_HOT_STATUS", "hot")
    ctx.storage_hot_reason = os.environ.get("TAU_STORAGE_HOT_REASON", "")
    raw_hot_mbps = os.environ.get("TAU_STORAGE_HOT_WRITE_MBPS", "")
    try:
        ctx.storage_hot_write_mbps = float(raw_hot_mbps) if raw_hot_mbps else None
    except ValueError:
        ctx.storage_hot_write_mbps = None
    # TAU_UPSTREAM_CHECKPOINT is set by the tau Go CLI on rayjob-eval
    # pods (head + workers). Plain training pods don't see it; default to
    # None so user code can reliably check `if ctx.upstream_checkpoint`.
    ctx.upstream_checkpoint = _envp("TAU_UPSTREAM_CHECKPOINT", "")
    ctx.resume_from = _envp("TAU_RESUME_FROM", "")
    ctx.is_remote = True
    return ctx


def _install_tau_shim(manifest=None):
    """Inject a minimal tau module into sys.modules.

    The researcher's source imports `import tau` (or `from tau import
    train, eval, Ctx`) and writes `@tau.train(...)` or `@tau.eval(...)`.
    On the cluster tau-py isn't installed, so we forge a stub module that
    produces the same handle shape (object with ``_tau_train_handle = True``
    or ``_tau_eval_handle = True`` plus a ``_fn`` attribute) the local SDK
    does.

    Calling the handle on-cluster raises (the wrapper invokes ``_fn(ctx)``
    directly with a populated Ctx; you should never call it yourself), and
    ``.submit()`` raises (would recurse).
    """

    class _ClusterCtxStub:
        # Only used for `tau.workloads.Ctx` type hints in user code; the
        # real ctx the wrapper passes in is built by _build_cluster_ctx.
        pass

    class _ClusterTrainHandle:
        # Real class with class-level dunders so `handle()` triggers
        # __call__ (instance attrs on SimpleNamespace would be ignored by
        # Python's special-method lookup).
        _tau_train_handle = True

        def __init__(self, fn, kwargs):
            self._fn = fn
            self._kwargs = kwargs
            self.__name__ = getattr(fn, "__name__", "train")

        def __call__(self, *a, **kw):
            raise RuntimeError(
                "tau-py: refusing to call the training function "
                "directly inside a cluster-submitted job. The wrapper "
                "invokes it for you with a populated Ctx."
            )

        def submit(self, *a, **kw):
            raise RuntimeError(
                "tau-py: refusing to .submit() from inside a "
                "cluster-submitted job (would recurse). Submit from "
                "your local machine, or from a CI runner."
            )

    class _ClusterEvalHandle:
        # Same shape as _ClusterTrainHandle but with the eval sentinel
        # so _find_handle can route to the right code path.
        _tau_eval_handle = True

        def __init__(self, fn, kwargs):
            self._fn = fn
            self._kwargs = kwargs
            self.__name__ = getattr(fn, "__name__", "eval")

        def __call__(self, *a, **kw):
            raise RuntimeError(
                "tau-py: refusing to call the eval function directly "
                "inside a cluster-submitted job. The wrapper invokes "
                "it for you with a populated Ctx."
            )

        def submit(self, *a, **kw):
            raise RuntimeError(
                "tau-py: refusing to .submit() from inside a "
                "cluster-submitted job (would recurse)."
            )

    def _train(*args, **kwargs):
        if args:
            raise TypeError("tau.train: pass parameters as keyword arguments")

        def decorator(fn):
            return _ClusterTrainHandle(fn, dict(kwargs))

        return decorator

    def _eval(*args, **kwargs):
        if args:
            raise TypeError("tau.eval: pass parameters as keyword arguments")

        def decorator(fn):
            return _ClusterEvalHandle(fn, dict(kwargs))

        return decorator

    config = types.ModuleType("tau.config")
    exec(_render_config_shim(manifest), config.__dict__)

    datasets = types.ModuleType("tau.datasets")
    exec(_TAU_SHIM_DATASETS, datasets.__dict__)
    entrypoints = types.ModuleType("tau.entrypoints")
    exec(_TAU_SHIM_ENTRYPOINTS, entrypoints.__dict__)
    jsonl = types.ModuleType("tau.jsonl")
    exec(_TAU_SHIM_JSONL, jsonl.__dict__)

    workloads = types.ModuleType("tau.workloads")
    workloads.train = _train
    workloads.eval = _eval
    workloads.Ctx = _ClusterCtxStub
    tau = types.ModuleType("tau")
    tau.__path__ = []
    tau.datasets = datasets
    tau.entrypoints = entrypoints
    tau.jsonl = jsonl
    tau.workloads = workloads
    # Mirror the local package's top-level exports so
    # `from tau import train, eval, Ctx` works on-cluster too.
    tau.train = _train
    tau.eval = _eval
    tau.Ctx = _ClusterCtxStub
    tau.SecretRef = config.SecretRef
    tau.call_staged_function = entrypoints.call_staged_function
    tau.config = config.config
    tau.dataset_file_reference = datasets.dataset_file_reference
    tau.load_config = config.load_config
    tau.load_staged_function = entrypoints.load_staged_function
    tau.load_staged_module = entrypoints.load_staged_module
    tau.pvc_mount = config.pvc_mount
    tau.read_jsonl_objects = jsonl.read_jsonl_objects
    tau.secret = config.secret
    tau.secret_ref = config.secret_ref
    tau.__all__ = [
        "Ctx",
        "SecretRef",
        "call_staged_function",
        "config",
        "dataset_file_reference",
        "datasets",
        "entrypoints",
        "eval",
        "jsonl",
        "load_config",
        "load_staged_function",
        "load_staged_module",
        "pvc_mount",
        "read_jsonl_objects",
        "secret",
        "secret_ref",
        "train",
        "workloads",
    ]
    sys.modules["tau"] = tau
    sys.modules["tau.datasets"] = datasets
    sys.modules["tau.entrypoints"] = entrypoints
    sys.modules["tau.jsonl"] = jsonl
    sys.modules["tau.workloads"] = workloads
    sys.modules["tau.config"] = config


def _user_module_name(path):
    name = pathlib.Path(path).stem
    if not name.isidentifier():
        sys.exit(
            "tau-py wrapper: staged user module filename must be an "
            "importable Python module name, got " + pathlib.Path(path).name
        )
    if name == "tau":
        sys.exit(
            "tau-py wrapper: staged user module filename " +
            pathlib.Path(path).name +
            " is reserved because it would shadow the cluster tau shim"
        )
    return name


def _ensure_user_module_dir_on_sys_path(path):
    module_dir = str(pathlib.Path(path).resolve().parent)
    if module_dir not in sys.path:
        sys.path.insert(0, module_dir)


def _load_user_module(path):
    module_name = _user_module_name(path)
    _ensure_user_module_dir_on_sys_path(path)
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        sys.exit("tau-py wrapper: cannot load user module at " + path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def _write_importable_tau_shim(root, manifest=None):
    tau_dir = pathlib.Path(root) / "tau"
    tau_dir.mkdir(parents=True, exist_ok=True)
    (tau_dir / "__init__.py").write_text(_TAU_SHIM_INIT)
    (tau_dir / "config.py").write_text(_render_config_shim(manifest))
    (tau_dir / "datasets.py").write_text(_TAU_SHIM_DATASETS)
    (tau_dir / "entrypoints.py").write_text(_TAU_SHIM_ENTRYPOINTS)
    (tau_dir / "workloads.py").write_text(_TAU_SHIM_WORKLOADS)
    (tau_dir / "jsonl.py").write_text(_TAU_SHIM_JSONL)


def _prepare_eval_worker_working_dir(ctx):
    import shutil
    import tempfile

    source = pathlib.Path(USER_MODULE_PATH)
    working_dir = pathlib.Path(tempfile.mkdtemp(prefix="tau-py-worker-"))
    shutil.copy2(source, working_dir / source.name)
    _write_importable_tau_shim(working_dir, getattr(ctx, "manifest", None))
    return working_dir


def _maybe_init_eval_ray_runtime_env(ctx):
    try:
        import ray
    except ModuleNotFoundError as exc:
        if exc.name == "ray":
            return
        raise
    if ray.is_initialized():
        return
    working_dir = _prepare_eval_worker_working_dir(ctx)
    ray.init(address="auto", runtime_env={"working_dir": str(working_dir)})


def _find_handle(module, kind):
    """Return the @tau.{kind} handle in module; exit with a clear error otherwise.

    `kind` is "train" or "eval". The wrapper picks which to look for based
    on the rendered manifest's eval.cpu_workers field (rayjob-eval pods
    have it set; rayjob/job pods don't). Same module can carry both
    handles — e.g. for the experiment.py pattern that the tau-py
    orchestrator submits as two separate RayJobs.
    """
    sentinel = "_tau_" + kind + "_handle"
    # Dedupe by object identity so `alias = train` (a re-export) doesn't
    # falsely trip the "multiple handles" guard.
    seen_ids = set()
    candidates = []
    for name in dir(module):
        obj = getattr(module, name)
        if not getattr(obj, sentinel, False):
            continue
        if id(obj) in seen_ids:
            continue
        seen_ids.add(id(obj))
        candidates.append((name, obj))
    if not candidates:
        sys.exit(
            "tau-py wrapper: no @tau." + kind +
            "-decorated function found in " + USER_MODULE_PATH
        )
    if len(candidates) > 1:
        names = ", ".join(n for n, _ in candidates)
        sys.exit(
            "tau-py wrapper: multiple @tau." + kind +
            "-decorated functions found (" + names + "); only one per "
            "module is supported in V1."
        )
    return candidates[0][1]


def _profile_runtime_rank():
    for key in ("TAU_RANK", "RANK", "WORLD_RANK", "OMPI_COMM_WORLD_RANK", "PMI_RANK"):
        value = os.environ.get(key, "")
        if value:
            return value
    try:
        from ray import train as _ray_train
        rank = _ray_train.get_context().get_world_rank()
        if rank is not None:
            return str(rank)
    except Exception:
        pass
    local_rank = os.environ.get("LOCAL_RANK", "")
    if local_rank:
        return local_rank
    return "0"


def _profile_rank_selected(runtime_rank):
    rank_filter = (os.environ.get("TAU_PROFILE_RANK", "0") or "0").strip().lower()
    if rank_filter == "all":
        return True, rank_filter
    ranks = [part.strip() for part in rank_filter.split(",") if part.strip()]
    return runtime_rank in ranks, rank_filter


def _safe_profile_rank(rank):
    safe = []
    for ch in str(rank):
        if ch.isalnum() or ch in ("_", ".", "-"):
            safe.append(ch)
        else:
            safe.append("-")
    return "".join(safe) or "unknown"


def _profile_seconds(key):
    raw = os.environ.get(key, "0")
    try:
        return max(0, int(raw or "0"))
    except ValueError:
        raise RuntimeError("tau profiler: " + key + " must be an integer second count, got " + repr(raw))


def _profile_utc_now():
    return datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _write_text_atomic(path, text):
    path = pathlib.Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp." + str(os.getpid()))
    with tmp.open("w") as f:
        f.write(text)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)
    _fsync_dir(path.parent)


def _write_profile_metadata(path, payload):
    path = pathlib.Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp." + str(os.getpid()))
    with tmp.open("w") as f:
        json.dump(payload, f, indent=2, sort_keys=True)
        f.write("\n")
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)
    _fsync_dir(path.parent)


def _write_profile_summary(path, payload):
    lines = [
        "# Tau profile artifact",
        "",
        "- run_id: " + str(payload.get("run_id", "")),
        "- namespace: " + str(payload.get("namespace", "")),
        "- mode: " + str(payload.get("mode", "")),
        "- rank: " + str(payload.get("rank", "")) + " (filter: " + str(payload.get("rank_filter", "")) + ")",
        "- host: " + str(payload.get("host", "")),
        "- command: " + str(payload.get("command", "")),
        "- warmup_seconds: " + str(payload.get("warmup_seconds", 0)),
        "- active_seconds: " + str(payload.get("active_seconds", 0)),
        "- tool_version: " + str(payload.get("tool_version", "")),
        "- raw_profile_path: " + str(payload.get("raw_profile_path", "")),
        "- sqlite_path: " + str(payload.get("sqlite_path", "")),
        "- metadata_path: " + str(payload.get("metadata_path", "")),
        "- started_at: " + str(payload.get("started_at", "")),
        "- completed_at: " + str(payload.get("completed_at", "")),
        "- exit_status: " + str(payload.get("exit_status", "")),
        "- target_exit_status: " + str(payload.get("target_exit_status", "")),
        "- completion_reason: " + str(payload.get("completion_reason", "")),
        "- export_status: " + str(payload.get("export_status", "")),
        "- error: " + str(payload.get("error", "")),
        "",
    ]
    _write_text_atomic(path, "\n".join(lines))


def _profile_tool_version(tool):
    res = subprocess.run([tool, "--version"], capture_output=True, text=True, check=False)
    text = (res.stdout or res.stderr or "").strip().splitlines()
    return text[0] if text else ""


def _profile_out_dir():
    return pathlib.Path(os.environ.get("TAU_PROFILE_OUT_DIR", "") or ("/data/checkpoints/finetunes/" + os.environ.get("TAU_PROFILE_RUN_ID", "unknown") + "/profile"))


def _profile_worker_base(host, pid):
    return _profile_out_dir() / ("ray-worker-" + _safe_profile_rank(host) + "-" + str(pid))


def _ray_worker_profile_runtime_env():
    mode = (os.environ.get("TAU_PROFILE_MODE", "") or "").strip().lower()
    if not mode:
        return {}
    if mode != "nsys":
        raise RuntimeError("tau profiler: unsupported TAU_PROFILE_MODE=" + repr(mode) + " (expected 'nsys')")
    active_seconds = _profile_seconds("TAU_PROFILE_ACTIVE_SEC")
    if active_seconds <= 0:
        raise RuntimeError("tau profiler: TAU_PROFILE_ACTIVE_SEC must be > 0 for Ray Train worker profiling")
    warmup_seconds = _profile_seconds("TAU_PROFILE_WARMUP_SEC")
    out_dir = _profile_out_dir()
    out_dir.mkdir(parents=True, exist_ok=True)
    config = {
        "t": "cuda,cudnn,cublas,nvtx,osrt",
        "o": str(out_dir / "ray-worker-%q{HOSTNAME}-%p"),
        "force-overwrite": "true",
        "stop-on-exit": "true",
        "capture-range": "cudaProfilerApi",
        "capture-range-end": "stop",
        "flush-on-cudaprofilerstop": "true",
        "export": "sqlite",
        "sample": "none",
        "cpuctxsw": "none",
    }
    return {"nsight": config}


def _cuda_profiler_api_call(name):
    import torch

    cudart = torch.cuda.cudart()
    fn = getattr(cudart, name)
    status = fn()
    if status not in (None, 0):
        raise RuntimeError("tau profiler: " + name + " returned " + str(status))


def _start_cuda_profile_window(warmup_seconds, active_seconds):
    stop_event = threading.Event()
    errors = []
    state = {"started": False, "stopped": False, "lock": threading.Lock()}

    def _stop_once():
        with state["lock"]:
            if not state.get("started") or state.get("stopped"):
                return
            _cuda_profiler_api_call("cudaProfilerStop")
            state["stopped"] = True

    def _timer():
        try:
            if warmup_seconds > 0 and stop_event.wait(warmup_seconds):
                return
            if stop_event.is_set():
                return
            with state["lock"]:
                _cuda_profiler_api_call("cudaProfilerStart")
                state["started"] = True
            if not stop_event.wait(active_seconds):
                _stop_once()
        except BaseException as exc:
            errors.append(repr(exc))

    thread = threading.Thread(target=_timer, name="tau-nsys-cuda-profiler-window", daemon=True)
    thread.start()
    return stop_event, thread, state, errors


def _finish_cuda_profile_window(stop_event, thread, state, errors):
    stop_event.set()
    with state["lock"]:
        should_stop = state.get("started") and not state.get("stopped")
    if should_stop:
        with state["lock"]:
            if state.get("started") and not state.get("stopped"):
                _cuda_profiler_api_call("cudaProfilerStop")
                state["stopped"] = True
    thread.join(timeout=5)
    if errors:
        raise RuntimeError("tau profiler: CUDA profiler API failed: " + "; ".join(errors))


def _run_profiled_worker(call_target):
    mode = (os.environ.get("TAU_PROFILE_MODE", "") or "").strip().lower()
    if not mode:
        return call_target()
    if mode != "nsys":
        raise RuntimeError("tau profiler: unsupported TAU_PROFILE_MODE=" + repr(mode) + " (expected 'nsys')")

    runtime_rank = _profile_runtime_rank()
    selected, rank_filter = _profile_rank_selected(runtime_rank)
    if not selected:
        print(
            "tau profiler: skipping rank " + runtime_rank + " (target rank " + rank_filter + ")",
            flush=True,
        )
        return call_target()

    active_seconds = _profile_seconds("TAU_PROFILE_ACTIVE_SEC")
    if active_seconds <= 0:
        raise RuntimeError("tau profiler: TAU_PROFILE_ACTIVE_SEC must be > 0 for Ray Train actor profiling")
    warmup_seconds = _profile_seconds("TAU_PROFILE_WARMUP_SEC")

    out_dir = _profile_out_dir()
    safe_rank = _safe_profile_rank(runtime_rank)
    base = out_dir / ("rank-" + safe_rank)
    raw_path = pathlib.Path(str(base) + ".nsys-rep")
    sqlite_path = pathlib.Path(str(base) + ".sqlite")
    metadata_path = pathlib.Path(str(base) + ".metadata.json")
    summary_path = pathlib.Path(str(base) + ".summary.md")
    host = os.environ.get("HOSTNAME", "")
    if not host:
        try:
            host = pathlib.Path("/etc/hostname").read_text().strip()
        except OSError:
            host = "unknown"
    host = host or "unknown"
    started_at = _profile_utc_now()
    tool = os.environ.get("TAU_PROFILE_TOOL", "nsys") or "nsys"
    worker_base = _profile_worker_base(host, os.getpid())
    worker_raw_path = pathlib.Path(str(worker_base) + ".nsys-rep")
    worker_sqlite_path = pathlib.Path(str(worker_base) + ".sqlite")
    command = "ray RunConfig(worker_runtime_env={'nsight': ...}) when supported"
    out_dir.mkdir(parents=True, exist_ok=True)

    def _payload(status, target_status, completion_reason, error_msg, completed_at, export_status, tool_version):
        return {
            "schema_version": 1,
            "run_id": os.environ.get("TAU_PROFILE_RUN_ID", ""),
            "namespace": os.environ.get("TAU_PROFILE_NAMESPACE", ""),
            "mode": mode,
            "rank": runtime_rank,
            "rank_filter": rank_filter,
            "host": host,
            "command": command,
            "warmup_seconds": warmup_seconds,
            "active_seconds": active_seconds,
            "tool_version": tool_version,
            "raw_profile_path": str(raw_path),
            "sqlite_path": str(sqlite_path),
            "worker_raw_profile_path": str(worker_raw_path),
            "worker_sqlite_path": str(worker_sqlite_path),
            "worker_pid": os.getpid(),
            "metadata_path": str(metadata_path),
            "summary_path": str(summary_path),
            "started_at": started_at,
            "completed_at": completed_at,
            "exit_status": status,
            "target_exit_status": target_status,
            "completion_reason": completion_reason,
            "export_status": export_status,
            "error": error_msg,
        }

    if shutil.which(tool) is None:
        completed_at = _profile_utc_now()
        err = "tau --profiler=nsys: " + tool + " not found in image"
        payload = _payload(127, 127, "tool-not-found", err, completed_at, "not-run", "")
        _write_profile_metadata(metadata_path, payload)
        _write_profile_summary(summary_path, payload)
        raise RuntimeError(err)

    tool_version = _profile_tool_version(tool)
    result = None
    target_status = 0
    target_error = ""
    exc_info = None
    capture_error = ""
    stop_event, capture_thread, capture_state, capture_errors = _start_cuda_profile_window(warmup_seconds, active_seconds)
    try:
        result = call_target()
    except BaseException as exc:
        target_status = 1
        target_error = repr(exc)
        exc_info = sys.exc_info()
    try:
        _finish_cuda_profile_window(stop_event, capture_thread, capture_state, capture_errors)
    except BaseException as exc:
        target_status = 1
        capture_error = repr(exc)
        if not target_error:
            target_error = capture_error
        if exc_info is None:
            exc_info = sys.exc_info()

    completed_at = _profile_utc_now()
    export_status = "pending"
    status = target_status
    completion_reason = "ray-worker-profile-pending"
    if target_status != 0:
        completion_reason = "capture-failed" if capture_error else "target-failed"
    payload = _payload(status, target_status, completion_reason, target_error, completed_at, export_status, tool_version)
    _write_profile_metadata(metadata_path, payload)
    _write_profile_summary(summary_path, payload)

    if exc_info is not None:
        raise exc_info[1].with_traceback(exc_info[2])
    return result


def _finalize_ray_worker_profiles(ctx, timeout_seconds=180):
    mode = (os.environ.get("TAU_PROFILE_MODE", "") or "").strip().lower()
    if not mode:
        return
    out_dir = _profile_out_dir()
    deadline = time.monotonic() + timeout_seconds
    metadata_paths = sorted(out_dir.glob("rank-*.metadata.json"))
    expected = int(os.environ.get("TAU_PROFILE_WORLD_SIZE", "0") or "0")
    if expected > 0 and (os.environ.get("TAU_PROFILE_RANK", "") or "").strip().lower() == "all":
        while len(metadata_paths) < expected and time.monotonic() < deadline:
            time.sleep(2)
            metadata_paths = sorted(out_dir.glob("rank-*.metadata.json"))
    if not metadata_paths:
        raise RuntimeError("tau profiler: no rank metadata files found in " + str(out_dir))

    missing = []
    for metadata_path in metadata_paths:
        try:
            payload = json.loads(metadata_path.read_text())
        except Exception as exc:
            missing.append(str(metadata_path) + " (metadata parse failed: " + str(exc) + ")")
            continue
        worker_raw = pathlib.Path(str(payload.get("worker_raw_profile_path") or ""))
        worker_sqlite = pathlib.Path(str(payload.get("worker_sqlite_path") or ""))
        final_raw = pathlib.Path(str(payload.get("raw_profile_path") or ""))
        final_sqlite = pathlib.Path(str(payload.get("sqlite_path") or ""))
        while worker_raw and not worker_raw.is_file() and time.monotonic() < deadline:
            time.sleep(2)
        if not worker_raw or not worker_raw.is_file():
            payload["completion_reason"] = "profile-missing"
            payload["exit_status"] = 1
            payload["error"] = "nsys report did not appear at " + str(worker_raw)
            payload["completed_at"] = _profile_utc_now()
            _write_profile_metadata(metadata_path, payload)
            _write_profile_summary(pathlib.Path(str(payload.get("summary_path") or metadata_path.with_suffix(".summary.md"))), payload)
            missing.append(str(worker_raw))
            continue
        if final_raw and worker_raw != final_raw:
            final_raw.parent.mkdir(parents=True, exist_ok=True)
            if final_raw.exists():
                final_raw.unlink()
            shutil.move(str(worker_raw), str(final_raw))
        if worker_sqlite.is_file() and final_sqlite and worker_sqlite != final_sqlite:
            if final_sqlite.exists():
                final_sqlite.unlink()
            shutil.move(str(worker_sqlite), str(final_sqlite))
        payload["completion_reason"] = "nsys-capture-range-complete"
        payload["exit_status"] = 0
        payload["export_status"] = "ok" if final_sqlite.is_file() else "not-found"
        payload["completed_at"] = _profile_utc_now()
        _write_profile_metadata(metadata_path, payload)
        _write_profile_summary(pathlib.Path(str(payload.get("summary_path") or metadata_path.with_suffix(".summary.md"))), payload)
    if missing:
        raise RuntimeError("tau profiler: missing Nsight report(s): " + ", ".join(missing))


def _multi_node_runtime_env(ctx=None):
    """Pip list shipped to worker pods via the RayJob's spec.runtimeEnvYAML.

    The Go renderer is the source of truth for the rendered RayJob CRD's
    runtime_env: it threads the manifest's `runtime.pip` block (now
    REQUIRED — tau ships no fallback) into the worker pod's pip list.
    This function exists for the per-actor `runtime_env` override path
    (RunConfig.worker_runtime_env when local Ray supports it) — it returns
    the same pip the renderer wrote into the CRD so all actors see a
    consistent environment.

    Workers do NOT run the head's bash entrypoint, so they would not have
    torch/etc without this. We ship via the RayJob CRD-level runtime_env
    (NOT ray.init's runtime_env), because by the time the wrapper calls
    ray.init(address="auto") the worker actors are already being placed
    and ray.init's runtime_env on a pre-existing cluster is a driver-side
    setting only.

    Raises ``RuntimeError`` when ``ctx.manifest`` lacks ``runtime.pip``.
    """
    if ctx is None:
        raise RuntimeError(
            "tau-py: _multi_node_runtime_env requires a ctx (tau ships "
            "no default pip list; declare runtime.pip in your manifest "
            "via extra_manifest)"
        )
    runtime_block = (ctx.manifest.get("runtime") or {}) if isinstance(getattr(ctx, "manifest", None), dict) else {}
    pip = runtime_block.get("pip") if isinstance(runtime_block, dict) else None
    if not pip:
        raise RuntimeError(
            "tau-py: ctx.manifest.runtime.pip is empty; declare your "
            "pip deps via @tau.train(extra_manifest={\"runtime\": "
            "{\"pip\": [...]}})"
        )
    return {"pip": list(pip)}


def _run_config_kwargs_for_worker_runtime_env(run_config_cls, worker_runtime_env):
    # Backward compatibility: Ray 2.39, used by the H200/RDMA runtime image,
    # does not accept RunConfig(worker_runtime_env=...). Newer Ray versions do,
    # so keep using it when available and otherwise rely on RayJob-level
    # runtime_env.
    if "worker_runtime_env" in inspect.signature(run_config_cls).parameters:
        return {"worker_runtime_env": worker_runtime_env}
    print(
        "tau-py wrapper: Ray RunConfig does not support worker_runtime_env; "
        "using RayJob-level runtime_env only.",
        flush=True,
    )
    return {}


def _wait_for_cluster_resources(ctx, timeout_s=180, interval_s=3):
    """Poll Ray's cluster view until all worker GPUs have registered.

    KubeRay submits the RayJob entrypoint when the head's dashboard is
    ready, not when worker pods have finished joining Ray. On cold
    starts (especially when Karpenter has to provision a new H200 node)
    this gap can be tens of seconds. An immediate assert would race
    that startup and fail healthy clusters; we poll instead and only
    fail after a bounded timeout with a clear snapshot.
    """
    import time
    import ray
    want = int(ctx.workers) * int(ctx.gpus)
    if want == 0:
        return
    deadline = time.monotonic() + timeout_s
    last_got = 0
    while time.monotonic() < deadline:
        got = int(ray.cluster_resources().get("GPU", 0))
        last_got = got
        if got >= want:
            if got != want:
                # Got more GPUs than expected (extra worker?). Surface
                # this as an error — silently overprovisioning is just
                # as bad a contract violation as underprovisioning.
                raise RuntimeError(
                    "tau-py wrapper: Ray sees " + str(got) +
                    " GPUs, expected exactly " + str(want) +
                    ". Extra worker pods registered — check Karpenter / "
                    "Kueue for a runaway scale-up."
                )
            return
        time.sleep(interval_s)
    nodes = ray.nodes()
    alive = sum(1 for n in nodes if n.get("Alive"))
    raise RuntimeError(
        "tau-py wrapper: timed out after " + str(timeout_s) + "s waiting "
        "for " + str(want) + " GPUs to register with Ray. Last seen: " +
        str(last_got) + " GPUs across " + str(alive) + " alive node(s) "
        "(of " + str(len(nodes)) + " total in ray.nodes()). Check "
        "workerGroupSpec.rayStartParams.num-gpus and the DRA claim "
        "template for both head and worker pods. See the TauGrid "
        "troubleshooting guide."
    )


def _run_multi_node(handle, ctx):
    """Wrap the user fn in TorchTrainer and gang-train across all GPUs.

    Ray Train's standard idiom is one worker actor per rank, with each
    actor pinned to one GPU. That makes plain torch.distributed / DDP /
    FSDP code work unchanged — WORLD_SIZE = workers*gpus, RANK is the
    global rank, and CUDA_VISIBLE_DEVICES is set to the assigned GPU.
    Setting num_workers=ctx.workers (one per pod) instead would give
    only 2 ranks each seeing 8 GPUs and force the user to do their own
    intra-node parallelism — a worse contract than "plain DDP works".

    Ray pickles the per-worker train_fn for shipment to worker actors. We do
    not close over `handle._fn`; workers re-load the staged user module by
    path and find the same handle by name.
    """
    import ray
    from ray.train import RunConfig, ScalingConfig
    from ray.train.torch import TorchConfig, TorchTrainer

    if not ray.is_initialized():
        ray.init(address="auto")

    _wait_for_cluster_resources(ctx)

    ctx_payload = {
        "name": ctx.name,
        "gpus": int(ctx.gpus),
        "workers": int(ctx.workers),
        "smoke_pairs": int(ctx.smoke_pairs),
        "manifest": ctx.manifest,
        "manifest_path": str(ctx.manifest_path) if ctx.manifest_path else None,
        "data_dir": str(ctx.data_dir),
        "hot_dir": str(ctx.hot_dir),
        "datasets_dir": str(ctx.datasets_dir),
        "checkpoints_dir": str(ctx.checkpoints_dir),
        "durable_datasets_dir": str(ctx.durable_datasets_dir),
        "durable_checkpoints_dir": str(ctx.durable_checkpoints_dir),
        "storage_hot_status": ctx.storage_hot_status,
        "storage_hot_reason": ctx.storage_hot_reason,
        "storage_hot_write_mbps": ctx.storage_hot_write_mbps,
        "is_remote": True,
    }
    handle_name = handle.__name__
    user_module_path = USER_MODULE_PATH
    gpu_workers = int(ctx.workers) * int(ctx.gpus)
    cpu_only = int(ctx.gpus) == 0
    total_workers = int(ctx.workers) if cpu_only else gpu_workers
    # Prefer TAU_NUM_WORKERS when set by the Go renderer.
    if os.environ.get("TAU_NUM_WORKERS"):
        total_workers = int(os.environ["TAU_NUM_WORKERS"])
    dist_backend = os.environ.get("TAU_DIST_BACKEND", "nccl" if not cpu_only else "gloo")
    config_shim_src = _render_config_shim(ctx.manifest)
    worker_runtime_env = _multi_node_runtime_env(ctx)
    worker_runtime_env.update(_ray_worker_profile_runtime_env())
    run_config_kwargs = _run_config_kwargs_for_worker_runtime_env(
        RunConfig, worker_runtime_env
    )

    def _train_loop(_config):
        # CPU-only jobs deliberately skip this check and omit the GPU
        # resource key from ScalingConfig below.
        import importlib.util as _ilu
        import os as _os
        import pathlib as _p
        import sys as _sys
        import types as _t
        import torch as _torch
        if not cpu_only:
            seen = _torch.cuda.device_count()
            if seen < 1:
                raise RuntimeError(
                    "tau-py wrapper: rank sees " + str(seen) +
                    " CUDA GPUs, expected at least 1 for a GPU Ray Train "
                    "worker. Check that the worker pod's "
                    "DRA claim attached and that resources_per_worker={'GPU': 1}."
                )
            if seen > 1:
                local_rank = int(_os.environ.get("LOCAL_RANK", "0") or "0")
                device = local_rank % seen
                print(
                    "tau-py wrapper: Ray Train worker sees " + str(seen) +
                    " CUDA GPUs; using LOCAL_RANK " + str(local_rank) +
                    " -> cuda:" + str(device) +
                    " for classic pod-level GPU visibility",
                    flush=True,
                )
                _torch.cuda.set_device(device)
        # Inline shim install (mirrors _install_tau_shim) — workers do
        # not have tau-py installed and the shim from the driver process
        # is not visible across actor processes. Includes eval as well as
        # train so that experiment.py files carrying both decorators load
        # cleanly on the worker (the worker only invokes the train fn —
        # eval lives on a separate RayJob with its own head pod — but the
        # whole user module must still be importable here).
        if "tau.workloads" not in _sys.modules:
            class _StubCtx:
                pass

            class _StubHandle:
                _tau_train_handle = True

                def __init__(self, fn, kwargs):
                    self._fn = fn
                    self._kwargs = kwargs
                    self.__name__ = getattr(fn, "__name__", "train")

                def __call__(self, *a, **kw):
                    raise RuntimeError(
                        "tau-py: refusing to call the training function "
                        "directly inside a Ray Train worker."
                    )

                def submit(self, *a, **kw):
                    raise RuntimeError(
                        "tau-py: refusing to .submit() from inside a "
                        "Ray Train worker."
                    )

            class _StubEvalHandle:
                _tau_eval_handle = True

                def __init__(self, fn, kwargs):
                    self._fn = fn
                    self._kwargs = kwargs
                    self.__name__ = getattr(fn, "__name__", "eval")

                def __call__(self, *a, **kw):
                    raise RuntimeError(
                        "tau-py: refusing to call the eval function "
                        "from a training worker."
                    )

                def submit(self, *a, **kw):
                    raise RuntimeError(
                        "tau-py: refusing to .submit() from inside a "
                        "Ray Train worker."
                    )

            def _train_dec(*a, **kw):
                if a:
                    raise TypeError(
                        "tau.train: pass parameters as keyword arguments"
                    )

                def _wrap(fn):
                    return _StubHandle(fn, dict(kw))

                return _wrap

            def _eval_dec(*a, **kw):
                if a:
                    raise TypeError(
                        "tau.eval: pass parameters as keyword arguments"
                    )

                def _wrap(fn):
                    return _StubEvalHandle(fn, dict(kw))

                return _wrap

            _cfg = _t.ModuleType("tau.config")
            exec(config_shim_src, _cfg.__dict__)
            _ds = _t.ModuleType("tau.datasets")
            exec(_TAU_SHIM_DATASETS, _ds.__dict__)
            _ep = _t.ModuleType("tau.entrypoints")
            exec(_TAU_SHIM_ENTRYPOINTS, _ep.__dict__)
            _jl = _t.ModuleType("tau.jsonl")
            exec(_TAU_SHIM_JSONL, _jl.__dict__)
            _wl = _t.ModuleType("tau.workloads")
            _wl.train = _train_dec
            _wl.eval = _eval_dec
            _wl.Ctx = _StubCtx
            _r = _t.ModuleType("tau")
            _r.__path__ = []
            _r.datasets = _ds
            _r.entrypoints = _ep
            _r.jsonl = _jl
            _r.workloads = _wl
            _r.train = _train_dec
            _r.eval = _eval_dec
            _r.Ctx = _StubCtx
            _r.SecretRef = _cfg.SecretRef
            _r.call_staged_function = _ep.call_staged_function
            _r.config = _cfg.config
            _r.dataset_file_reference = _ds.dataset_file_reference
            _r.load_config = _cfg.load_config
            _r.load_staged_function = _ep.load_staged_function
            _r.load_staged_module = _ep.load_staged_module
            _r.pvc_mount = _cfg.pvc_mount
            _r.read_jsonl_objects = _jl.read_jsonl_objects
            _r.secret = _cfg.secret
            _r.secret_ref = _cfg.secret_ref
            _r.__all__ = [
                "Ctx",
                "SecretRef",
                "call_staged_function",
                "config",
                "dataset_file_reference",
                "datasets",
                "entrypoints",
                "eval",
                "jsonl",
                "load_config",
                "load_staged_function",
                "load_staged_module",
                "pvc_mount",
                "read_jsonl_objects",
                "secret",
                "secret_ref",
                "train",
                "workloads",
            ]
            _sys.modules["tau"] = _r
            _sys.modules["tau.datasets"] = _ds
            _sys.modules["tau.entrypoints"] = _ep
            _sys.modules["tau.jsonl"] = _jl
            _sys.modules["tau.workloads"] = _wl
            _sys.modules["tau.config"] = _cfg

        module_name = _p.Path(user_module_path).stem
        module_dir = str(_p.Path(user_module_path).resolve().parent)
        if module_dir not in _sys.path:
            _sys.path.insert(0, module_dir)
        spec = _ilu.spec_from_file_location(module_name, user_module_path)
        if spec is None or spec.loader is None:
            raise RuntimeError(
                "tau-py wrapper: worker cannot load user module at " + user_module_path
            )
        mod = _ilu.module_from_spec(spec)
        _sys.modules[module_name] = mod
        spec.loader.exec_module(mod)

        worker_handle = None
        for nm in dir(mod):
            obj = getattr(mod, nm)
            if not getattr(obj, "_tau_train_handle", False):
                continue
            if nm == handle_name or worker_handle is None:
                worker_handle = obj
                if nm == handle_name:
                    break
        if worker_handle is None:
            raise RuntimeError(
                "tau-py wrapper: worker found no @tau.train handle in " + user_module_path
            )

        # Rebuild ctx as a SimpleNamespace; user code reads attrs only.
        # NOTE: ctx.gpus reflects the ORIGINAL per-pod GPU count (e.g. 8),
        # not the logical per-rank allocation. User code that wants the
        # process-visible GPU count should use torch.cuda.device_count().
        worker_ctx = _t.SimpleNamespace(**{
            k: (_p.Path(v) if k.endswith("_dir") or k == "manifest_path" else v)
            for k, v in ctx_payload.items()
            if not (k == "manifest_path" and v is None)
        })
        if ctx_payload.get("manifest_path") is None:
            worker_ctx.manifest_path = None

        result = _run_profiled_worker(lambda: worker_handle._fn(worker_ctx))
        _finalize_train_artifacts(worker_ctx)
        return result

    # Apply execution.configs overrides from TAU_RAY_TRAIN_CONFIG_JSON.
    torch_config_kwargs = {"backend": dist_backend}
    scaling_config_kwargs = {
        "num_workers": total_workers,
        "use_gpu": not cpu_only,
        "resources_per_worker": {"CPU": 1} if cpu_only else {"GPU": 1},
        "placement_strategy": "SPREAD",
    }
    failure_config_kwargs = {}

    _ray_train_config_raw = os.environ.get("TAU_RAY_TRAIN_CONFIG_JSON", "")
    if _ray_train_config_raw:
        import json as _json
        try:
            _ray_train_config = _json.loads(_ray_train_config_raw)
        except _json.JSONDecodeError as e:
            raise RuntimeError(
                "tau-py wrapper: TAU_RAY_TRAIN_CONFIG_JSON is malformed: " + str(e)
            ) from e
        if "torch_config" in _ray_train_config:
            torch_config_kwargs.update(_ray_train_config["torch_config"])
        if "scaling_config" in _ray_train_config:
            scaling_config_kwargs.update(_ray_train_config["scaling_config"])
        if "failure_config" in _ray_train_config:
            failure_config_kwargs.update(_ray_train_config["failure_config"])

    if failure_config_kwargs:
        from ray.train import FailureConfig
        run_config_kwargs["failure_config"] = FailureConfig(**failure_config_kwargs)

    trainer = TorchTrainer(
        _train_loop,
        torch_config=TorchConfig(**torch_config_kwargs),
        scaling_config=ScalingConfig(**scaling_config_kwargs),
        run_config=RunConfig(**run_config_kwargs),
    )
    return trainer.fit()


def _maybe_init_single_pod_distributed():
    """Initialize torch.distributed when torchrun spawned multiple ranks.

    The multi-node path uses Ray Train, which owns process-group setup. The
    single-pod path runs the user function directly, so torchrun-provided
    WORLD_SIZE/RANK/LOCAL_RANK need a small SDK-owned bootstrap.
    """
    world_size = int(os.environ.get("WORLD_SIZE", "1") or "1")
    if world_size <= 1:
        return None

    import torch
    import torch.distributed as dist

    if not dist.is_available():
        raise RuntimeError(
            "tau-py wrapper: torch.distributed is not available but "
            "WORLD_SIZE=" + str(world_size) + " requires it"
        )

    initialized_by_wrapper = False
    if not dist.is_initialized():
        backend = os.environ.get("TAU_DIST_BACKEND", "nccl" if torch.cuda.is_available() else "gloo")
        dist.init_process_group(backend=backend)
        initialized_by_wrapper = True

    if torch.cuda.is_available():
        local_rank = int(os.environ.get("LOCAL_RANK", "0") or "0")
        torch.cuda.set_device(local_rank)

    return dist if initialized_by_wrapper else None


def _destroy_single_pod_distributed(dist):
    if dist is not None and dist.is_initialized():
        dist.destroy_process_group()


def _is_primary_process():
    return int(os.environ.get("RANK", "0") or "0") == 0


def _validate_artifact_path(value):
    if not isinstance(value, str):
        raise RuntimeError("tau-py wrapper: artifacts.checkpoint must be a string")
    checkpoint = value.strip()
    if not checkpoint:
        raise RuntimeError("tau-py wrapper: artifacts.checkpoint must not be empty")
    p = pathlib.PurePosixPath(checkpoint)
    if p.is_absolute() or any(part in ("", ".", "..") for part in p.parts):
        raise RuntimeError(
            "tau-py wrapper: artifacts.checkpoint must be a relative pod "
            "path without '.' or '..' segments (got " + repr(value) + ")"
        )
    return p.as_posix()


def _checkpoint_artifact_from_manifest(manifest):
    artifacts = manifest.get("artifacts")
    if artifacts is None:
        return None
    if not isinstance(artifacts, dict):
        raise RuntimeError("tau-py wrapper: manifest artifacts must be a mapping")
    checkpoint = artifacts.get("checkpoint")
    if checkpoint is None:
        return None
    return _validate_artifact_path(checkpoint)


def _artifact_sources(ctx, artifact):
    artifact_path = pathlib.PurePosixPath(artifact)
    candidates = [
        ctx.checkpoints_dir.joinpath(*artifact_path.parts),
        ctx.checkpoints_dir / "finetunes" / ctx.name / artifact_path,
        ctx.durable_checkpoints_dir / ctx.name / artifact_path,
        ctx.durable_checkpoints_dir / "finetunes" / ctx.name / artifact_path,
        ctx.durable_checkpoints_dir / "finetunes" / ctx.name / "artifacts" / artifact_path,
    ]
    seen = set()
    for candidate in candidates:
        key = candidate.as_posix()
        if key not in seen:
            seen.add(key)
            yield candidate


def _artifact_destination(ctx, artifact):
    return ctx.durable_checkpoints_dir / "finetunes" / ctx.name / "artifacts" / pathlib.PurePosixPath(artifact)


def _fsync_dir(path):
    fd = os.open(str(path), os.O_RDONLY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def _format_bytes(value):
    value = float(value)
    for unit in ("B", "KiB", "MiB", "GiB", "TiB"):
        if value < 1024 or unit == "TiB":
            if unit == "B":
                return str(int(value)) + " " + unit
            return ("%.1f" % value).rstrip("0").rstrip(".") + " " + unit
        value /= 1024
    return str(int(value)) + " B"


def _copy_file_with_progress(src, dst):
    src = pathlib.Path(src)
    dst = pathlib.Path(dst)
    total = src.stat().st_size
    progress = total >= _COPY_PROGRESS_MIN_BYTES
    copied = 0
    next_report = _COPY_PROGRESS_STEP_BYTES
    last_report = time.monotonic()
    if progress:
        print(
            "tau-py wrapper: copying checkpoint artifact file " +
            src.as_posix() + " to " + dst.as_posix() +
            " (size=" + _format_bytes(total) + ")",
            flush=True,
        )
    with src.open("rb") as fsrc, dst.open("wb") as fdst:
        while True:
            chunk = fsrc.read(_COPY_BUFFER_BYTES)
            if not chunk:
                break
            fdst.write(chunk)
            copied += len(chunk)
            now = time.monotonic()
            if progress and (
                copied >= total or
                copied >= next_report or
                now - last_report >= _COPY_PROGRESS_INTERVAL_SECONDS
            ):
                pct = 100.0 if total == 0 else (copied * 100.0 / total)
                print(
                    "tau-py wrapper: copied checkpoint artifact file " +
                    _format_bytes(copied) + "/" + _format_bytes(total) +
                    " (%.1f%%)" % pct,
                    flush=True,
                )
                last_report = now
                while copied >= next_report:
                    next_report += _COPY_PROGRESS_STEP_BYTES
        fdst.flush()
        os.fsync(fdst.fileno())
    return dst


def _copy_artifact_dir(src, dst):
    dst.mkdir(parents=True, exist_ok=True)
    for child in src.iterdir():
        target = dst / child.name
        if child.is_dir():
            _copy_artifact_dir(child, target)
        elif child.is_file():
            _copy_file_with_progress(child, target)
        else:
            raise RuntimeError(
                "tau-py wrapper: checkpoint artifact contains unsupported "
                "path " + child.as_posix()
            )
    _fsync_dir(dst)


def _copy_artifact(src, dst):
    dst.parent.mkdir(parents=True, exist_ok=True)
    if src.resolve(strict=False) == dst.resolve(strict=False):
        return
    if src.is_dir():
        tmp = dst.parent / (dst.name + ".tmp." + str(os.getpid()))
        if tmp.exists():
            shutil.rmtree(tmp)
        _copy_artifact_dir(src, tmp)
        if dst.exists():
            if dst.is_dir():
                shutil.rmtree(dst)
            else:
                dst.unlink()
        os.replace(tmp, dst)
        _fsync_dir(dst.parent)
        return
    tmp = dst.parent / (dst.name + ".tmp." + str(os.getpid()))
    _copy_file_with_progress(src, tmp)
    os.replace(tmp, dst)
    _fsync_dir(dst.parent)


def _artifact_stats(path):
    if path.is_file():
        st = path.stat()
        return {
            "kind": "file",
            "size_bytes": int(st.st_size),
            "file_count": 1,
            "mtime": datetime.datetime.fromtimestamp(st.st_mtime, datetime.timezone.utc).isoformat(),
        }
    size = 0
    count = 0
    latest = path.stat().st_mtime
    for root, _dirs, files in os.walk(path):
        for name in files:
            p = pathlib.Path(root) / name
            st = p.stat()
            size += int(st.st_size)
            count += 1
            latest = max(latest, st.st_mtime)
    if count == 0:
        raise RuntimeError(
            "tau-py wrapper: declared checkpoint artifact directory "
            + path.as_posix()
            + " contains no files"
        )
    return {
        "kind": "directory",
        "size_bytes": size,
        "file_count": count,
        "mtime": datetime.datetime.fromtimestamp(latest, datetime.timezone.utc).isoformat(),
    }


def _write_json_atomic(path, payload):
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp." + str(os.getpid()))
    with tmp.open("w") as f:
        json.dump(payload, f, indent=2, sort_keys=True)
        f.write("\n")
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)
    _fsync_dir(path.parent)


def _safe_registry_segment(value, default="unknown"):
    value = (value or "").strip()
    if not value:
        return default
    out = []
    previous_dash = False
    for ch in value.lower():
        if ("a" <= ch <= "z") or ("0" <= ch <= "9"):
            out.append(ch)
            previous_dash = False
        elif ch in ("-", "_", ".", " "):
            if not previous_dash:
                out.append("-")
                previous_dash = True
    slug = "".join(out).strip("-")
    return slug or default


def _model_metadata_from_manifest(manifest):
    raw = manifest.get("model") if isinstance(manifest, dict) else None
    if not isinstance(raw, dict):
        raw = {}
    tags = raw.get("tags") if isinstance(raw.get("tags"), dict) else {}
    metadata = {
        "name": _safe_registry_segment(raw.get("name")),
        "base": raw.get("base") or "",
        "task": raw.get("task") or "",
        "tags": {str(k): str(v) for k, v in tags.items()},
        "primary_metric": raw.get("primary_metric") or "",
        "metric_direction": raw.get("metric_direction") or "",
    }
    if metadata["metric_direction"] not in ("lower", "higher", ""):
        metadata["metric_direction"] = ""
    return metadata


def _metric_candidates(ctx):
    return [
        ctx.durable_checkpoints_dir / "finetunes" / ctx.name / "metrics.json",
        ctx.durable_checkpoints_dir / ctx.name / "metrics.json",
        ctx.durable_checkpoints_dir / ctx.name / "train-metrics.json",
        ctx.durable_checkpoints_dir / ctx.name / "eval-metrics.json",
    ]


def _load_json_if_exists(path):
    if not path.is_file():
        return None, ""
    with path.open() as f:
        return json.load(f), path.as_posix()


def _numeric_metrics(value, prefix=""):
    out = {}
    if isinstance(value, dict):
        for key, child in value.items():
            if not isinstance(key, str):
                continue
            child_prefix = key if not prefix else prefix + "." + key
            out.update(_numeric_metrics(child, child_prefix))
        return out
    if isinstance(value, bool):
        return out
    if isinstance(value, (int, float)):
        out[prefix] = float(value)
    return out


def _load_metrics_summary(ctx):
    for path in _metric_candidates(ctx):
        raw, raw_path = _load_json_if_exists(path)
        if raw is None:
            continue
        return {
            "path": raw_path,
            "numeric": _numeric_metrics(raw),
            "raw": raw,
        }
    return {"path": "", "numeric": {}, "raw": {}}


def _primary_metric(model_metadata, numeric_metrics):
    name = model_metadata.get("primary_metric") or ""
    if not name:
        for candidate in ("loss", "eval.loss", "train.loss", "score", "accuracy"):
            if candidate in numeric_metrics:
                name = candidate
                break
    if not name:
        return {}
    metric = {"name": name}
    if name in numeric_metrics:
        metric["value"] = numeric_metrics[name]
    direction = model_metadata.get("metric_direction") or ("lower" if "loss" in name else "higher")
    metric["direction"] = direction
    return metric


def _model_registry_record(ctx, artifact_index, artifact_index_path, completed_at):
    metadata = _model_metadata_from_manifest(ctx.manifest)
    metrics = _load_metrics_summary(ctx)
    model_name = metadata["name"] or "unknown"
    canonical_path = ctx.durable_checkpoints_dir / "finetunes" / ctx.name / "model.json"
    registry_path = ctx.durable_checkpoints_dir.parent / "model-registry" / "models" / model_name / "runs" / (ctx.name + ".json")
    return {
        "schema_version": 1,
        "kind": "tau.model",
        "model": model_name,
        "run": ctx.name,
        "namespace": os.environ.get("POD_NAMESPACE", ""),
        "resource_name": os.environ.get("TAU_RESOURCE_NAME", ""),
        "created_at": completed_at.isoformat(),
        "completed_at": completed_at.isoformat(),
        "record_path": canonical_path.as_posix(),
        "registry_path": registry_path.as_posix(),
        "artifacts_index": artifact_index_path.as_posix(),
        "model_metadata": metadata,
        "tags": metadata.get("tags", {}),
        "metrics_path": metrics["path"],
        "metrics": metrics["numeric"],
        "primary_metric": _primary_metric(metadata, metrics["numeric"]),
        "artifacts": artifact_index.get("artifacts", []),
        "storage_probe": artifact_index.get("storage_probe", {}),
    }


def _write_model_registry_records(ctx, record):
    canonical_path = pathlib.Path(record["record_path"])
    registry_path = pathlib.Path(record["registry_path"])
    _write_json_atomic(canonical_path, record)
    _write_json_atomic(registry_path, record)


def _finalize_train_artifacts(ctx):
    if not _is_primary_process():
        return
    artifact = _checkpoint_artifact_from_manifest(ctx.manifest)
    if artifact is None:
        return
    src = next((candidate for candidate in _artifact_sources(ctx, artifact) if candidate.exists()), None)
    if src is None:
        tried = ", ".join(p.as_posix() for p in _artifact_sources(ctx, artifact))
        raise RuntimeError(
            "tau-py wrapper: declared checkpoint artifact " + repr(artifact) +
            " was not found after training succeeded. Tried: " + tried
        )
    dst = _artifact_destination(ctx, artifact)
    started = datetime.datetime.now(datetime.timezone.utc)
    start = time.monotonic()
    _copy_artifact(src, dst)
    duration_ms = int((time.monotonic() - start) * 1000)
    completed = datetime.datetime.now(datetime.timezone.utc)
    stats = _artifact_stats(dst)
    record = {
        "name": "checkpoint",
        "manifest_path": artifact,
        "source_path": src.as_posix(),
        "durable_path": dst.as_posix(),
        "status": "ready",
        "upload_started_at": started.isoformat(),
        "upload_completed_at": completed.isoformat(),
        "upload_duration_ms": duration_ms,
    }
    record.update(stats)
    index = {
        "schema_version": 1,
        "run": ctx.name,
        "namespace": os.environ.get("POD_NAMESPACE", ""),
        "resource_name": os.environ.get("TAU_RESOURCE_NAME", ""),
        "created_at": completed.isoformat(),
        "hot_root": ctx.checkpoints_dir.as_posix(),
        "durable_root": ctx.durable_checkpoints_dir.as_posix(),
        "storage_probe": {
            "status": ctx.storage_hot_status,
            "reason": ctx.storage_hot_reason,
            "write_mbps": ctx.storage_hot_write_mbps,
        },
        "artifacts": [record],
    }
    artifact_index_path = ctx.durable_checkpoints_dir / "finetunes" / ctx.name / "artifacts.json"
    _write_json_atomic(artifact_index_path, index)
    model_record = _model_registry_record(ctx, index, artifact_index_path, completed)
    _write_model_registry_records(ctx, model_record)
    print(
        "tau-py wrapper: finalized checkpoint artifact " + repr(artifact) +
        " to " + dst.as_posix() +
        " (duration_ms=" + str(duration_ms) + ")",
        flush=True,
    )


def main():
    parser = argparse.ArgumentParser(description="tau-py cluster wrapper")
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--smoke-pairs", type=int, default=0)
    args, _unknown = parser.parse_known_args()

    ctx = _build_cluster_ctx(args.manifest, args.smoke_pairs)
    _install_tau_shim(ctx.manifest)
    module = _load_user_module(USER_MODULE_PATH)

    # Dispatch based on the manifest's eval.cpu_workers field, mirroring
    # the Go-side IsEval() check. rayjob-eval pods have cpu_workers > 0;
    # plain training pods don't (cpu_workers absent or 0).
    eval_block = ctx.manifest.get("eval") or {}
    is_eval = int(eval_block.get("cpu_workers", 0) or 0) > 0
    kind = "eval" if is_eval else "train"
    handle = _find_handle(module, kind)
    if is_eval:
        _maybe_init_eval_ray_runtime_env(ctx)
        upstream = ctx.upstream_checkpoint
        upstream_str = str(upstream) if upstream else "<unset>"
        print(
            "tau-py wrapper: invoking " + handle.__name__ +
            " (kind=eval, gpus=" + str(ctx.gpus) +
            ", cpu_workers=" + str(int(eval_block.get("cpu_workers", 0))) +
            ", upstream=" + upstream_str + ")",
            flush=True,
        )
        handle._fn(ctx)
        return
    print(
        "tau-py wrapper: invoking " + handle.__name__ +
        " (kind=train, workers=" + str(ctx.workers) + ", gpus=" + str(ctx.gpus) +
        ", smoke_pairs=" + str(ctx.smoke_pairs) + ")",
        flush=True,
    )
    # Managed RayJobs set TAU_NUM_WORKERS and always execute user code through
    # dedicated Ray Train workers. Plain Jobs omit it and execute locally.
    if os.environ.get("TAU_NUM_WORKERS"):
        _run_multi_node(handle, ctx)
        _finalize_ray_worker_profiles(ctx)
    else:
        dist_to_destroy = _maybe_init_single_pod_distributed()
        try:
            _run_profiled_worker(lambda: handle._fn(ctx))
            _finalize_train_artifacts(ctx)
        finally:
            try:
                _destroy_single_pod_distributed(dist_to_destroy)
            except Exception as exc:
                print(
                    "tau-py wrapper: process group teardown error after train "
                    "completion (non-fatal): " + str(exc),
                    flush=True,
                )


if __name__ == "__main__":
    main()
'''


def render_wrapper(user_module_filename: str) -> str:
    """Substitute the user-module filename into the wrapper template."""
    replacements = {
        "__USER_MODULE_FILENAME__": repr(user_module_filename),
        "__TAU_SHIM_DATASETS_SOURCE__": repr(_cluster_helper_source("datasets.py")),
        "__TAU_SHIM_ENTRYPOINTS_SOURCE__": repr(_cluster_helper_source("entrypoints.py")),
        "__TAU_SHIM_JSONL_SOURCE__": repr(_cluster_helper_source("jsonl.py")),
    }
    rendered = CLUSTER_WRAPPER_TEMPLATE
    for marker, value in replacements.items():
        rendered = rendered.replace(marker, value)
    return rendered


def _cluster_helper_source(filename: str) -> str:
    """Read the real helper source that the cluster shim embeds."""
    return resources.files("tau").joinpath(filename).read_text(encoding="utf-8")
