apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gpu-monitoring.configMapName" . }}
  namespace: {{ include "gpu-monitoring.namespace" . }}
  labels:
    {{- include "gpu-monitoring.labels" . | nindent 4 }}
immutable: true
data:
{{ include "gpu-monitoring.configMapData" . | indent 2 }}
