apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpu-monitoring.executableBundleName" . }}
  namespace: {{ include "gpu-monitoring.namespace" . }}
  labels:
    {{- include "gpu-monitoring.labels" . | nindent 4 }}
type: Opaque
immutable: true
stringData:
{{ include "gpu-monitoring.executableBundleData" . | indent 2 }}
