{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ include "gpu-monitoring.namespace" . }}
  labels:
    {{- include "gpu-monitoring.labels" . | nindent 4 }}
{{- end }}
