{{- if .Values.collector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "adx-mon.serviceAccountName" (dict "root" . "component" "collector") }}
  namespace: {{ include "adx-mon.namespace" . }}
  labels:
    {{- include "adx-mon.componentLabels" (dict "root" . "component" "collector") | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
